### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Justman10000** [comment]
@MorrisJobke

**Comment by MorrisJobke** [comment]
Thanks, but I guess this repo is abandoned 🙈

**Comment by Justman10000** [comment]
> Thanks, but I guess this repo is abandoned 🙈

Can still be merged, just like #15... Would suggest doing it that way, after that you could also archive the repo...

**Comment by Justman10000** [comment]
Why is [nextcloud.com](/nextcloud/nextcloud.com) now used instead of [website](/nextcloud/website)?

**Comment by MorrisJobke** [comment]
Because it was never adopted 🤷‍♂️

Ask @jospoortvliet about this

**Pull request closed without merging**
