### PR TITLE
[WIP] Implement homepage

### PR DESCRIPTION
**Pull request by Espina2**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Could you remove the .DS_Store files, then this looks good 👍

**Comment by jospoortvliet** [comment]
Hmm I get a white page and these errors:
Building sites … ERROR 2018/02/22 20:47:25 Error while rendering "home" in "": template: /home/jospoortvliet/source/website/themes/nextcloud/layouts/index.html:26:23: executing "/home/jospoortvliet/source/website/themes/nextcloud/layouts/index.html" at <index .Site.Data.css...>: error calling index: index of untyped nil
ERROR 2018/02/22 20:47:25 Error while rendering "page" in "blog/": template: /home/jospoortvliet/source/website/themes/nextcloud/layouts/post/single.html:26:23: executing "/home/jospoortvliet/source/website/themes/nextcloud/layouts/post/single.html" at <index .Site.Data.css...>: error calling index: index of untyped nil
ERROR 2018/02/22 20:47:25 Error while rendering "404" in "": template: /home/jospoortvliet/source/website/themes/nextcloud/layouts/404.html:26:23: executing "/home/jospoortvliet/source/website/themes/nextcloud/layouts/404.html" at <index .Site.Data.css...>: error calling index: index of untyped nil

**Comment by Espina2** [comment]
If you are in my branch, you have to run npm install, to install all the dependencies, and after gulp watch, so it compiles the assets.

**Comment by Espina2** [comment]
Gulp deals with all asset compilation such as transforming the scss in css, and create a bundle for all the javascript files and transpile it (transform new javascript in old javascript) so we have better browser coverage. 

Try this:
npm install 
npm install -g gulp
gulp watch

The first two you just need to run one time.

**Comment by jospoortvliet** [comment]
Ok, all done - still not working ;-)

no errors from gulp and hugo (that's an improvement). It is quite broken:
screenshot_20180227_145534

Not sure what causes it... There's at least some CSS loaded. WIP?

**Comment by Espina2** [comment]
Its working, you have the current state Dude if see on the PR it's a Work in progress. This is will not be a project in where you put one day of work and is all done. It will take time, the more we have more faster will be.

**Pull request closed without merging**
